"""Data loaders and window builder for the strategy-construction package.

Three layers:

    1. Raw loaders — thin wrappers around stml.io that enforce canonical sort
       order and optionally apply the leakage boundary.

    2. OOF probability loader — loads the training-period calibrated OOF
       probabilities (date, instrument, p_hat_oof). Raises a clear error if the
       artifact is missing rather than silently fabricating values.

       IMPORTANT: This artifact does NOT yet exist. It must be generated by
       running CPCV(6,2) on the training events in run_locked_strategy.py and
       saving the Platt-calibrated OOF scores to:
           data/oof_meta_probabilities.csv
       Schema: date (= t_signal), instrument, p_hat_oof
       Coverage: date < BOUNDARY = 2022-01-01 ONLY.

    3. Window builder — assembles a (T × d+2) feature matrix for a single
       instrument at each signal date:
           channels 0..d-1 : rolling OHLCV-derived features (d features)
           channel d       : primary side  s ∈ {-1, 0, +1}
           channel d+1     : calibrated OOF probability p̂ ∈ [0, 1]
       This is the input tensor for the neural models (VSN+LSTM, TFT).
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

from stml.io import load_data, load_clean_data, load_returns_panel  # noqa: F401
from stml.new_work import config


# ---------------------------------------------------------------------------
# 1. Raw loaders
# ---------------------------------------------------------------------------


def load_ohlcv(data_dir: Optional[Path] = None) -> pd.DataFrame:
    """Long-format OHLCV DataFrame, sorted by (instrument, date)."""
    ohlcv, _ = load_data(data_dir)
    return ohlcv  # already sorted by load_data


def load_ohlcv_for_instrument(
    inst: str, data_dir: Optional[Path] = None
) -> pd.DataFrame:
    """OHLCV for a single instrument; date-indexed, sorted ascending."""
    ohlcv = load_ohlcv(data_dir)
    df = ohlcv[ohlcv["instrument"] == inst].copy()
    df = df.set_index("date").sort_index()
    df.index = pd.to_datetime(df.index)
    return df


def load_signals(data_dir: Optional[Path] = None) -> pd.DataFrame:
    """Wide-format primary signals: date-indexed, columns = 11 instruments.

    Values are in {-1, 0, +1}. Date range: 2020-01-03 to ~2022-06-29.
    """
    _, signals = load_data(data_dir)
    df = signals.set_index("date").sort_index()
    df.index = pd.to_datetime(df.index)
    return df


# ---------------------------------------------------------------------------
# 2. OOF calibrated probability loader
# ---------------------------------------------------------------------------


def load_oof_probabilities(
    path: Optional[Path] = None,
    *,
    enforce_boundary: bool = True,
) -> pd.DataFrame:
    """Load training-period OOF calibrated probabilities.

    The artifact must be generated externally before calling this function.
    Expected schema:
        date        — t_signal (DatetimeIndex after parse)
        instrument  — ticker string
        p_hat_oof   — Platt-calibrated CPCV(6,2) out-of-fold probability ∈ [0, 1]
    Coverage: date < BOUNDARY (2022-01-01) ONLY.

    Parameters
    ----------
    path
        Override the default path (config.OOF_PROBA_PATH).
    enforce_boundary
        If True (default), drop any rows with date >= BOUNDARY so no leakage
        can occur even if the file was accidentally written beyond the cut.

    Raises
    ------
    FileNotFoundError
        If the artifact file does not exist.
    ValueError
        If required columns are missing.
    """
    p = Path(path or config.OOF_PROBA_PATH)
    if not p.exists():
        raise FileNotFoundError(
            f"\n"
            f"  OOF meta-probability artifact not found at:\n"
            f"    {p}\n\n"
            f"  This file must be generated before using the neural models or SOPS.\n"
            f"  Expected schema:\n"
            f"    date (= t_signal), instrument, p_hat_oof\n"
            f"  Expected coverage:\n"
            f"    date < {config.BOUNDARY.date()} only\n\n"
            f"  To generate: run CPCV(6,2) via run_locked_strategy.run_cpcv_oof()\n"
            f"  on the training events, Platt-calibrate the OOF scores, and save\n"
            f"  the result to the path above."
        )

    df = pd.read_csv(p, parse_dates=["date"])
    required = {"date", "instrument", "p_hat_oof"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(
            f"OOF probability file {p} is missing columns: {missing}\n"
            f"Required columns: {required}"
        )

    df["date"] = pd.to_datetime(df["date"])
    if enforce_boundary:
        n_before = len(df)
        df = df[df["date"] < config.BOUNDARY].copy()
        n_dropped = n_before - len(df)
        if n_dropped > 0:
            import warnings
            warnings.warn(
                f"Dropped {n_dropped} rows with date >= BOUNDARY "
                f"({config.BOUNDARY.date()}) from OOF probability file.",
                stacklevel=2,
            )

    return df.sort_values(["instrument", "date"]).reset_index(drop=True)


def load_oos_probabilities(
    path: Optional[Path] = None,
) -> pd.DataFrame:
    """Load the sealed OOS meta-model predictions (test period only).

    This is the existing `outputs/metamodel_predictions.csv`. Columns:
        instrument, date, t1, side, ret, bin, raw_proba, calibrated_proba, weight
    Coverage: 2021-10-21 → 2022-06-29 (the model champion test set).
    """
    p = Path(path or config.OOS_PROBA_PATH)
    if not p.exists():
        raise FileNotFoundError(f"OOS predictions not found at {p}")
    df = pd.read_csv(p, parse_dates=["date"])
    return df.sort_values(["instrument", "date"]).reset_index(drop=True)


# ---------------------------------------------------------------------------
# 3. (d+2)-channel window builder
# ---------------------------------------------------------------------------


def build_feature_window(
    ohlc: pd.DataFrame,
    signals: pd.DataFrame,
    oof_probas: pd.DataFrame,
    inst: str,
    *,
    lookback: int = config.LOOKBACK_L,
    feature_cols: Optional[list[str]] = None,
    vol_series: Optional[pd.Series] = None,
) -> tuple[np.ndarray, np.ndarray, pd.DatetimeIndex]:
    """Build a (T, lookback, d+2) input tensor for a single instrument.

    Each row t of the tensor is a lookback-bar window ending at date t:
        channels 0..d-1 : OHLCV-derived features, optionally vol-normalised
        channel d       : primary side s ∈ {-1, 0, +1} (constant across window)
        channel d+1     : OOF calibrated probability p̂ ∈ [0, 1] (current bar only)

    When `vol_series` is provided (annualised EWMA σ), every price feature in
    each bar is divided by σ_daily = σ_ann / √252, making the inputs
    scale-invariant across instruments and volatility regimes.

    Parameters
    ----------
    ohlc
        Date-indexed OHLCV DataFrame for `inst`.
    signals
        Wide-format signal panel, columns = instruments.
    oof_probas
        OOF probability DataFrame from load_oof_probabilities.
    inst
        Instrument ticker.
    lookback
        Number of bars per window.
    feature_cols
        OHLCV-derived feature names. Default: [log_ret, log_hl, log_co].
    vol_series
        Annualised EWMA σ series (DatetimeIndex aligned to `ohlc`).
        When provided, price features are divided by σ_daily = vol / √252.
        Must be causal (σ_t uses only data up to t).

    Returns
    -------
    X : np.ndarray, shape (T, lookback, d+2)
    y : np.ndarray, shape (T,)
    dates : pd.DatetimeIndex, shape (T,)
    """
    if feature_cols is None:
        feature_cols = ["log_ret", "log_hl", "log_co"]

    ohlc = ohlc.sort_index()

    # Build raw price features (causal — no lookahead).
    feats = pd.DataFrame(index=ohlc.index)
    feats["log_ret"] = np.log(ohlc["close"] / ohlc["close"].shift(1))
    feats["log_hl"] = np.log(
        ohlc["high"].clip(lower=1e-8) / ohlc["low"].clip(lower=1e-8)
    )
    feats["log_co"] = np.log(
        ohlc["close"].clip(lower=1e-8) / ohlc["open"].clip(lower=1e-8)
    )
    feats = feats[feature_cols]

    # Vol-normalise: divide price features by σ_daily = σ_ann / √252.
    if vol_series is not None:
        vol_ann = vol_series.reindex(feats.index).ffill()
        daily_sigma = (vol_ann / np.sqrt(config.TRADING_DAYS)).clip(lower=1e-8)
        feats = feats.div(daily_sigma, axis=0)

    # OOF probability index for this instrument.
    inst_oof = (
        oof_probas[oof_probas["instrument"] == inst]
        .set_index("date")["p_hat_oof"]
        .sort_index()
    )

    # Primary signal for this instrument.
    if inst not in signals.columns:
        raise KeyError(f"Instrument {inst!r} not found in signals panel")
    inst_signal = signals[inst].dropna()

    signal_dates = inst_signal.index.intersection(inst_oof.index)

    windows_X: list[np.ndarray] = []
    windows_y: list[float] = []
    valid_dates: list[pd.Timestamp] = []

    ohlc_dates = feats.index

    for dt in signal_dates:
        pos = ohlc_dates.get_loc(dt) if dt in ohlc_dates else None
        if pos is None or pos < lookback:
            continue

        window = feats.iloc[pos - lookback + 1: pos + 1].values  # (lookback, d)
        if np.any(~np.isfinite(window)):
            continue

        side  = float(inst_signal.loc[dt])
        p_hat = float(inst_oof.loc[dt])

        side_channel = np.full((lookback, 1), side, dtype=float)
        p_channel    = np.zeros((lookback, 1), dtype=float)
        p_channel[-1, 0] = p_hat

        x = np.concatenate([window, side_channel, p_channel], axis=1)
        windows_X.append(x)
        windows_y.append(side)
        valid_dates.append(dt)

    if not windows_X:
        d = len(feature_cols)
        return (
            np.empty((0, lookback, d + 2), dtype=float),
            np.empty(0, dtype=float),
            pd.DatetimeIndex([]),
        )

    X = np.stack(windows_X, axis=0)
    y = np.array(windows_y, dtype=float)
    dates = pd.DatetimeIndex(valid_dates)
    return X, y, dates
